version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./database/table-products.sql:/docker-entrypoint-initdb.d/table-products.sql
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: user

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile.springboot
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - postgres
