# Etapa 1: Construcción de la aplicación Spring Boot
FROM openjdk:17-jdk-alpine AS springboot-build
WORKDIR /app
COPY ./backend/producttable/target/producttable-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
